import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Annoucementbar from "./component/Annoucementbar";
import Header from "./component/Header";
import Footer from "./component/Footer";
import Consulting from "./component/Consulting";

// ✅ Poppins font setup
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
        <Annoucementbar />
        <Header />
        {children}
        <Consulting 
          title="Consulting"
          description="Let a registered conveyancer manage your settlement with confidence."
          imageUrl="/home-insurance-coverage-estate-residential 1.webp"
          buttonText="Chat With Us"
          buttonUrl="https://wa.me/61433101353"
          
        />
        <Footer 
          description="Contact us to learn more about the quality service we provide – the service you deserve!"
        />
      </body>
    </html>
  );
}